language: d
addons:
  ssh_known_hosts: vps1.cattermole.co.nz
matrix:
  include:
  - d: dmd-2.069.2
before_install:
- openssl aes-256-cbc -K $encrypted_8e44accaed0a_key -iv $encrypted_8e44accaed0a_iv
  -in deploy_key.enc -out deploy_key -d
script:
- dub build streameradminbot:main --compiler=${DC} --build=release
before_deploy:
- chmod +x deploy.sh
deploy:
  provider: script
  script: bash ./deploy.sh
  skip_cleanup: true
env:
  global:
    secure: Re/Uwhhz5G0Von10eeuQhJh+9KQWo7qf2KhNTopBg+Pb0/n/sLNi1mX/KuzU23DFmshV4nVqUy1ZauoViUpgfq7mg3K2cmCmO03lxqzX2KJnamb8IJ7z0TB6G4Z0nG6LeW3X2dzOYGJMmN42Rlh6uuzGB4cWEa6yJTRMfcW4f/jBnJySpl/ZYuRIMElY5ZdhOdQZlsL91k1Puq1++hnpEzebtVm4vgJUGKbHab0H/ASkUAjlvLA7Ptpq+icLoqKQVf2PepNnRK5F7aKSe4pWEHP/yNI3+CldBqKXO4o4RkjXem1yps/xWRW2R07JgggacCU+ee1c4kqSVE4qBvd1kqWbBiLy9Z2GSFKLpViB/9NBzA0D8dqZTSM2BrXugrsS2udCbIrRfGe4ATPM4DglUlx+yYGA8eAM26kN9zGUCPYiQhzHgBX8mrPraC82Kvtqt60uKnkhIdiAGyEkyK0sYcADIJ3ePtJnM3q0t3yaEFegH/W2mkfembULOpM7qjJtCqUx0UKd+6j07BW5tQMoXonnryblRfernt7kvRXBCIRXS7l4rBYtooimPX0YLNWmNsFfy2DWIoDIQOYKDbccL1OqV9dp2e+YN08deDZKqOkx9jYVyY92arsuvBkk3P6/2reiV/zPfWhdtIyDWNDK3RrFOGJa3bya4IUQ51+BHvQ=
