language: d
addons:
  ssh_known_hosts:
    - vps1.cattermole.co.nz
matrix:
  include:
    - d: dmd-2.069.2
script:
  - dub build streameradminbot:main --compiler=${DC} --build=release
before_deploy:
  - chmod +x deploy.sh
deploy:
  provider: script
  script: bash ./deploy.sh
  skip_cleanup: true
