language: d
addons:
  ssh_known_hosts: vps1.cattermole.co.nz
matrix:
  include:
  - d: dmd-2.069.2
before_install:
- openssl aes-256-cbc -K $encrypted_8e44accaed0a_key -iv $encrypted_8e44accaed0a_iv
  -in deploy_key.enc -out deploy_key -d
script:
- dub build streameradminbot:main --compiler=${DC} --build=release
before_deploy:
- chmod +x deploy.sh
deploy:
  provider: script
  script: bash ./deploy.sh
  skip_cleanup: true
env:
  global:
    secure: B/OS+UuB3WX9DKKtkxZgZQ+yCijKwS0OgtFONgiy7LQjjcTARZn5IPrGkktQC5L1Ddi9FlrOmbqAURXL428/6/zniXirp/mcNbnccqptvtyPhiXFCvKOuAsHb0a4ZcvarotJ9uqIzIhsTQPtVvusJjcEPXZM5x7WItjwV12Kf4FH/o4Oaxjh7bHhz8Wy7Sbaz7TvermGTKYWcg9hVTj+f1Q12+utvPSeH0fEUwhK4TkSppAmCWjGu5cZql3gp4dcMRLivS56rqgC7CNNcXUtw+gWu5CB1HRpp+yQdh/AQcJmCh0CiTYVk5J9LMj3yePN9FqV6DJj7fKIKdoTp3Pkv/X3wy1sFN7wDD6iBSvUTLVAM5kUtIt6zZowUlCGAxTRECbrNhDn6kBjsFBOjQU3jR0EhdtON80oFI+YsJjYPE89PQ5GetXtpoDTHgDietbncN7eVnq/pLy7+C7R/hsZPf18jGYvO8H50Z4mTRmQAxVEV/sEuXAgnxEkQ9YhCbDfcgSFCJ+KWPzrOx751rQdYS32iEI2qLG+6f28r1w6HcPFgGO/B1W0BnMaBg6DNYcNggY+ereJxAXvzfTu3pE9B8qR32gXmCNsybilDmNA6hfK030w3LH0qRd/z8hjx/IkwJGns+kjoaFO3UVO7VYY3P/mf8coosP89CM2xLVcrho=
